//
// Created by Christoph Schramm on 07.12.18.
//

#ifndef PARKETEER_HUB_CC3100_H
#define PARKETEER_HUB_CC3100_H

#define CONFIG_SPI_SIMPLELINK_DRV_NAME "SimpleLinkSPI"
#define CONFIG_SPI_SIMPLELINK_PRIORITY 80


#define CONFIG_SPI_SIMPLELINK_SPI_NAME "SPI_0"
#define CONFIG_SPI_SIMPLELINK_SPI_FREQ_0 20000000
#define CONFIG_SPI_SIMPLELINK_SPI_SLAVE 0
#define CONFIG_SPI_SIMPLELINK_GPIO_SPI_CS 1
#define CONFIG_SPI_SIMPLELINK_SPI_BUFFER_SIZE 256


#define CONFIG_SPI_FLASH_W25QXXDV_GPIO_SPI_CS_DRV_NAME "GPIO_1"
#define CONFIG_SPI_FLASH_W25QXXDV_GPIO_SPI_CS_PIN 11
#define CONFIG_SPI_FLASH_W25QXXDV_GPIO_CS_WAIT_DELAY 0

#define CONFIG_SPI_FLASH_W25QXXDV_GPIO_NHIB_DRV_NAME "GPIO_0"
#define CONFIG_SPI_FLASH_W25QXXDV_GPIO_NHIB_PIN 26

#define CONFIG_SPI_FLASH_W25QXXDV_GPIO_IRQ_DRV_NAME "GPIO_0"
#define CONFIG_SPI_FLASH_W25QXXDV_GPIO_IRQ_PIN 27

#include <spi.h>
int TestSpi();
void DiagIrqHandler(void);

struct spi_simplelink_data {
	struct device *spi;
#if defined(CONFIG_SPI_SIMPLELINK_GPIO_SPI_CS)
	struct spi_cs_control cs_ctrl;
#endif /* CONFIG_SPI_FLASH_W25QXXDV_GPIO_SPI_CS */
	struct spi_config spi_cfg;
#if defined(CONFIG_MULTITHREADING)
	struct k_sem sem;
#endif /* CONFIG_MULTITHREADING */
};

#endif //PARKETEER_HUB_CC3100_H
